# Generated by Django 4.2.3 on 2023-09-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=100)),
                ('experience_years', models.CharField(max_length=100)),
                ('experience_address', models.CharField(max_length=100)),
                ('experience_lvl', models.CharField(max_length=100)),
                ('experience_description', models.TextField()),
            ],
        ),
    ]
