# Generated by Django 4.2.3 on 2023-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_rename_experience_name_experience_experience_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_course',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
