# Generated by Django 4.2.3 on 2023-09-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Languages', models.CharField(max_length=100)),
            ],
        ),
    ]
