# Generated by Django 4.2.3 on 2023-09-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0007_myproject_rename_languages_languages_languages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProject',
        ),
    ]
