# Generated by Django 4.2.3 on 2023-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_star', models.IntegerField()),
                ('card_effect', models.TextField()),
                ('card_image',models.ImageField(upload_to='app_cards/card_images')),
            ],
        ),
    ]
