# Generated by Django 4.2.3 on 2023-09-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0002_myproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProject',
        ),
    ]
